# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gbricot <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/24 16:46:22 by gbricot           #+#    #+#              #
#    Updated: 2023/09/24 17:27:28 by gbricot          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =		HI_THIS_IS_BRAIN

CPPFLAGS =	-Wall -Wextra -Werror

CC =		g++

SRC =		main.cpp

$(NAME):
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)

all:

clean:
		rm -f $(NAME)

re:		clean $(NAME)
