# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gbricot <gbricot@student.42perpignan.fr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/24 16:46:22 by gbricot           #+#    #+#              #
#    Updated: 2023/09/28 12:58:37 by gbricot          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =		HI_THIS_IS_BRAIN

CPPFLAGS =	-Wall -Wextra -Werror -std=c++98

CC =		c++

SRC =		main.cpp

$(NAME):
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)

all:

clean:
		@rm -f $(NAME)

re:		clean $(NAME)
